### ISSUE TITLE
Le réseau Wifi "IOT" n'apparaît pas

### ISSUE THREAD

**Issue by r4adi0GaX2** [gkallenborn/HomeFW#1]
Bonjour,

Après avoir suivi les étapes une par une, le réseau Wifi "IOT" n'apparaît pas... en plus de cela m'a Raspberry Pi 3B+ affiche le message "No wireless interfaces found" (même si j'arrive à mi connecter en ssh).

Merci!

![Captura de Pantalla 2019-06-15 a les 1 10 16](https://user-images.githubusercontent.com/50443359/59543246-57faa600-8f0a-11e9-8c3d-b868d0038d35.png)

![Captura de Pantalla 2019-06-15 a les 11 14 33](https://user-images.githubusercontent.com/50443359/59549506-e39e2200-8f5e-11e9-875a-03b94529d2bb.png)

**Comment by gkallenborn** [comment]
Bonjour r4adi0GaX2. Je vois que vous vous connectez au Raspberry Pi depuis un MacBook Air. De votre remarque ("même si j'arrive à me connecter en SSH"), je déduis que vous vous connectez en SSH au travers de l'interface Wi-Fi du Raspberry Pi. Si c'est le cas, cela ne peut pas marcher: l'interface Wi-Fi ne peut pas être à la fois un point de connexion terminal et un point d'accès. Si vous utilisez SSH pour configurer le RPi , il faut que la connexion passe par le port Ethernet. Pour ma part, j'ai tout programmé directement sur le RPi, en connectant un écran et un clavier. 

Par ailleurs, pouvez-vous me montrer ce que vous avez dans les différents fichiers de configuration?

**Comment by r4adi0GaX2** [comment]
Bonjour, merci de votre réponse, je me connecte bien en ssh, mais à travers le port éther Éthernet... Je vais quande essayer de faire comme vous avez dit et de tout configurer directement sur la raspberry.

-------- Message d'origine --------

**Comment by gkallenborn** [comment]
Bonjour. Avec les versions Raspbian récentes, la configuration du logiciel "hostapd" que j'ai utilisé n'est plus valable. J'ai mis à jour le fichier "configurations.txt". Cela devrait fonctionner maintenant.
